# Generated by Django 4.1.5 on 2023-01-20 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, max_length=255, null=True)),
                ('cc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('bcc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_subject', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('plain_message', models.TextField(blank=True, null=True)),
                ('html_message', models.TextField(blank=True, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Ready to send'), (9, 'Send')], default=0)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatorid_email', to=settings.AUTH_USER_MODEL)),
                ('updaterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updaterid_email', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='f_mail_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
