# Generated by Django 4.1.5 on 2023-01-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='relationname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
