# Generated by Django 4.1.5 on 2023-01-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_alter_relation_relationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='sendmethod',
            field=models.IntegerField(choices=[(1, 'E-mail'), (2, 'Print')], default=1),
        ),
    ]
