# Generated by Django 4.1.5 on 2023-01-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('days_in_front', models.PositiveIntegerField(default=0)),
                ('on_each_side', models.PositiveIntegerField(default=3)),
                ('on_ends', models.PositiveIntegerField(default=0)),
                ('email_display_name', models.CharField(default='Eveningred', max_length=50)),
                ('email_from', models.EmailField(default='noreply@bosschapp.nl', max_length=100)),
                ('email_reply_to', models.EmailField(default='info@bosschapp.nl', max_length=100)),
                ('email_logo', models.CharField(blank=True, max_length=250, null=True)),
                ('email_to_accountancy', models.EmailField(blank=True, max_length=100, null=True)),
                ('conditions', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('regulations', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('homepage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('aboutuspage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('contactpage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('instagrampage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('facebookpage', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('conditiontypeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditiontypeid_configuration', to='master.conditiontype')),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatorid_configuration', to=settings.AUTH_USER_MODEL)),
                ('paymenttypeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paymenttypeid_configuration', to='master.paymenttype')),
                ('updaterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updaterid_configuration', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
