# Generated by Django 4.1.5 on 2023-02-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_remove_configuration_default_materials_projectid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='days_history',
            field=models.PositiveIntegerField(default=14),
        ),
    ]
