# Generated by Django 4.1.5 on 2023-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('app_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_name', models.CharField(blank=True, max_length=50, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('messagetype', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.JSONField(blank=True, default=dict, null=True)),
                ('severity', models.IntegerField(choices=[(5, 'Highest'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'Lowest')], default=3)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
