# Generated by Django 4.1.5 on 2023-02-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_relationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee_read',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee_write',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
    ]
