# Generated by Django 4.1.5 on 2023-01-20 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.IntegerField(choices=[(0, 'Actief'), (-1, 'Inactief')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('articlegroupid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articlegroupid_article', to='master.articlegroup')),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatorid_article', to=settings.AUTH_USER_MODEL)),
                ('unittypeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unittypeid_article', to='master.unittype')),
                ('updaterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updaterid_article', to=settings.AUTH_USER_MODEL)),
                ('vattypeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vattypeid_article', to='master.vattype')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
