# Generated by Django 4.1.5 on 2023-01-25 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relations', '0003_alter_relation_sendmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('number', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('suffix', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('postalcode', models.CharField(blank=True, default='', max_length=6, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('fulladdress', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Actief'), (-1, 'Inactief')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatorid_project', to=settings.AUTH_USER_MODEL)),
                ('relationid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationid_project', to='relations.relation')),
                ('updaterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updaterid_project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
