# Generated by Django 4.1.5 on 2023-01-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
