# Generated by Django 4.1.5 on 2023-02-22 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_alter_relation_sendmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_startdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateTimeField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amountmaterials', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchasingcosts', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processdate', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatorid_material', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectid_material', to='projects.project')),
                ('relationid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relationid_material', to='relations.relation')),
                ('updaterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updaterid_material', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userid_material', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuedate', models.DateTimeField(null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amounthours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('processdate', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creatorid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creatorid_hour', to=settings.AUTH_USER_MODEL)),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projectid_hour', to='projects.project')),
                ('updaterid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updaterid_hour', to=settings.AUTH_USER_MODEL)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userid_hour', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
