# Generated by Django 4.1.5 on 2023-02-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_material_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='creatorid',
        ),
        migrations.RemoveField(
            model_name='material',
            name='projectid',
        ),
        migrations.RemoveField(
            model_name='material',
            name='relationid',
        ),
        migrations.RemoveField(
            model_name='material',
            name='updaterid',
        ),
        migrations.RemoveField(
            model_name='material',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Hour',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
