# Generated by Django 4.1.5 on 2023-02-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['description'], 'permissions': [('process_administration', 'Can process project')]},
        ),
    ]
