# Generated by Django 4.1.5 on 2023-02-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_rename_relationid_material_customerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='issuedate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='processdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
