# Generated by Django 4.1.5 on 2023-02-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_issuedate_alter_material_processdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='amountmaterials',
        ),
    ]
