# Generated by Django 4.1.5 on 2023-03-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_alter_hour_issuedate_alter_hour_processdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hour',
            name='processdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
